Trainer:
  exp_group_name: HARDVS
  exp_num: 1e-5->1e-6 b24
  GPU_ids: [4,5,6,7]
  lr: 1e-5
  min_lr: 1e-6
  weight_decay: 0.05
  epoch: 10
  accumulation_steps: 1 # gradient accumulation, if not 0, remember lr *= accumulation_steps
  print_freq: 1
  Precision: fp16 # CLIP model default is float16
  seed: 101 # 3407 42 114514

MODEL:
  Load_Path: "/home/jinjing/zhoujiazhou/ExACT_github/Result/test-w/HARDVS/HARDVS-[90.10].bin"
  BACKBONE:
    Name: "ViT-B/16"
    Path:
    # CLIP model default is float16
    PRE_ENCODING: "fp16"
    #Download path to PRE_trained_model
    PRE_trained_model: '/home/jinjing/zhoujiazhou/ExACT_github/pretrained_CLIP/ViT-B-16.pt'
  EventEncoder:
    train_clip_backbone: True
    # feature output from the No.3 ViT block, -1 denotes output whithout the low-level ferature
    use_cross_frame_prompts: True # TODO ablation
    use_event_modality_prompts: True # TODO ablation
    num_event_modality_prompts: 16
    use_temporal_encoding: True # TODO ablation
    Low_level_feature_idx: [1]
  TextEncoder:
    init_ctx: True # TODO ablation
    CTX_INIT: "A series of photos recording human action for" #"A series of photos recording human action for" # A sketch image of a
    # length of text prompts
    leranable_ctx: True # TODO ablation
    N_CTX: 16 # TODO ablation
    use_event_bias_textual_prompts: False
  Conceptualizing_Alignment:
    num_concept: 1  # 32 16  8  4   2 TODO ablation
    concept_dim: 512 # 16 32 64 128 256 TODO ablation
    sample_num: 5

Dataset:
  Input_size: [224,224]
  Train:
    Path: "/home/jinjing/zhoujiazhou/ExACT_github/Dataloader/HARDVS/HARDVS_sampled_train_6_3_1.txt"
    Batch_size: 24  # TODO ablation
    Representation: 'gray_scale' # mlp_learned, frame, gray_scale, rgb # TODO ablation
    Agumentation: False
  Val:
    Path: "/home/jinjing/zhoujiazhou/ExACT_github/Dataloader/HARDVS/HARDVS_sampled_test_6_3_1.txt"
    Batch_size: 24 # TODO ablation
    Representation: 'gray_scale' # mlp_learned, frame, gray_scale, rgb # TODO ablation
    Agumentation: False
  Classnames: "/home/jinjing/zhoujiazhou/ExACT_github/Dataloader/HARDVS/HARDVS_300_class.json"

LossFunction:
  loss_sigma_threshold: 15000
  loss_cross_entroy: False # TODO ablation
  loss_cross_entroy_ori: False # TODO ablation
  loss_logsigma_sum: True # TODO ablation
  loss_SmoothL1Loss_txt: True # TODO ablation
  loss_SmoothL1Loss_ev: True # TODO ablation




